name: Docker Image Production

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Time
        id: time
        uses: josStorer/get-current-time@v2
        with:
          format: DD/MM/YYYY HH:mm
          timezone: Asia/Bangkok
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kugetreg-2023:latest --build-arg NEXT_PUBLIC_BUILD_MESSAGE="อัพเดทเมื่อ ${{ steps.time.outputs.formattedTime }}" .
      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/kugetreg-2023:latest
